{{- range .Values.eniconfigs }}
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: eniconfig
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  securityGroups:
    - {{ $.Values.securityGroupId }}
  subnet: {{ .subnetId }}
{{- end }}
